name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  PLUGIN_NAME: obsidian-weread-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
